name: my_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  equatable: ^2.0.3

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
